#!/bin/bash
# TODO: comment out the script
if [ $# -eq 0 ]; then
  echo warning: need the name of test directory, e.g., $0 changed-test-method-body
  exit
fi
# TODO: extend the script to work with multiple tests # google for "bash shift"
simple=$1
cd ${simple}
test=$(pwd)
# for debug # echo test directory is: ${test}

ekstazi_version=4.3.1
junit_stuff=$HOME/.m2/repository/junit/junit/4.11/junit-4.11.jar:$HOME/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

function compile() {
  echo compile $1
  find -name "*.java" > sources.txt
  javac -cp ${junit_stuff} @sources.txt 
}

function copy_and_compile() {
  echo copy $1 to $out
  
  cp -rf ${test}/$1 ${out}
  compile ${out}
}


function run_ekstazi() {
  echo running Ekstazi in ${out}
  cd ${out}

  if [ -f ${test}/class ]; then
    class=$(cat ${test}/class)
  else
    class=$(find -name "*Test*.class" | sed -e 'sX^\./XX' -e 's/.class$//' -e 'sX/X.X')
  fi

  java -javaagent:$HOME/.m2/repository/org/ekstazi/org.ekstazi.core/${ekstazi_version}/org.ekstazi.core-${ekstazi_version}.jar=mode=junit -cp .:${junit_stuff} org.junit.runner.JUnitCore ${class}
}


out=$HOME/tmp/${simple}
rm -rf ${out}
mkdir -p ${out}
cd ${out}
copy_and_compile v1/*
# TODO: change the script to run in the same folder
run_ekstazi | tee ${out}/log1

copy_and_compile v2/*
run_ekstazi | tee ${out}/log2

<${out}/log2 grep OK | sed -e 's/OK (//' -e 's/ test//' -e 's/s//' -e 's/)//' | diff - ${test}/expected >>${out}/log2
if [ $? -eq 0 ]; then
  echo Expected Tests:
  cat ${test}/expected
  echo Actual Tests:
  <${out}/log2 grep OK | sed -e 's/OK (//' -e 's/ test//' -e 's/s//' -e 's/)//'  | tee ${out}/actual
  echo PASSED: ${simple}
else
  echo Expected Tests:
  cat ${test}/expected
  echo Actual Tests:
  <${out}/log2 grep OK | sed -e 's/OK (//' -e 's/ test//' -e 's/s//' -e 's/)//'  | tee ${out}/actual
  echo FAILED: ${simple}
fi
